DROP DATABASE IF EXISTS triqui;
CREATE DATABASE triqui;
USE triqui;

CREATE TABLE juego (
  id INT NOT NULL AUTO_INCREMENT,
  jugador1 VARCHAR(50) NOT NULL,
  jugador2 VARCHAR(50) NOT NULL,
  dataTime DATETIME NULL,
  PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;


